apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-secret-loki
  namespace: {{ .Values.loki_config.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}

stringData: 
  access_key_id: {{ .Values.minio_config.secret.access_key }}
  access_key_secret: {{ .Values.minio_config.secret.secret_key }}
  bucketnames: {{ .Values.minio_config.secret.bucket_name }}
  endpoint: https://{{ include "minio.fullname" . }}-api.{{ .Values.ocp_config.domain }}
  region: {{ .Values.minio_config.region }}