---
apiVersion: v1
kind: Namespace
metadata:
  name:  openshift-cluster-observability-operator
  labels:
    openshift.io/cluster-monitoring: "true" 
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  namespace: openshift-cluster-observability-operator
  name: openshift-cluster-observability-operator
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-observability-operator
  namespace: openshift-cluster-observability-operator
spec:
  channel: {{ .Values.observability_config.channel }}
  installPlanApproval: {{ .Values.observability_config.approval }}
  name: cluster-observability-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.observability_config.version }}