apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "buildah-from-git.fullname" . }}-pvc
  labels:
    {{- include "buildah-from-git.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.pvc.size | default "1Gi" }}
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}