---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "minio.fullname" . }}-secret
  labels:
    {{- include "minio.labels" . | nindent 4 }}
stringData:
  minio_root_user: {{ .Values.minio_config.secret.access_key }}
  minio_root_password: {{ .Values.minio_config.secret.secret_key }}
