apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-thanos-bucket-config
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: {{ .Values.minio_config.secret.bucket_name }}
      endpoint: {{ include "minio.fullname" . }}-api.{{ .Values.ocp_config.domain }}
      insecure: false
      access_key: {{ .Values.minio_config.secret.access_key }}
      secret_key: {{ .Values.minio_config.secret.secret_key }}