FROM registry.access.redhat.com/ubi9/python-312:9.6-1747333115

USER 0
COPY src .
RUN chown -R 1001:0 ./
RUN yum install nmap -y \
    && yum clean all \
    && rm -rf /var/cache/yum
USER 1001

RUN pip install -r requirements.txt

EXPOSE 5000
EXPOSE 513
EXPOSE 514
EXPOSE 22
EXPOSE 23
EXPOSE 20 21
EXPOSE 135 137 139
EXPOSE 445
EXPOSE 111
EXPOSE 143
EXPOSE 110
EXPOSE 80
EXPOSE 25
EXPOSE 2049

ENTRYPOINT ["python", "app.py"]
