kind: Secret
apiVersion: v1
metadata:
  name: buildah-from-git-quay-pull-secret
  namespace: python-app
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjbWd0WldVdFkzSmxlV1Z6YldFcmRYTmxjakV3TVRwRVYxVkJUVXhRUjA5VVYwb3hURWRLVjFveU1EY3lUa3d5UTBOSFVEWkxUVWRaV1ZGU1IwNVlPRXBJU3psSFRrdFJXbGhDUkVwTFVVcElVVEJJVXpaViIsCiAgICAgICJlbWFpbCI6ICIiCiAgICB9CiAgfQp9
type: kubernetes.io/dockerconfigjson
